// AI layer.
// - If OPENAI_API_KEY is set, each stage is generated by an LLM (JSON mode).
// - Otherwise (or if the LLM call fails) a deterministic local engine tuned for
//   the Algerian (DZ) streetwear / retail market produces the same JSON shape.

const OPENAI_KEY = process.env.OPENAI_API_KEY;
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-4o-mini';
const OPENAI_BASE = process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1';

export const aiProvider = () => (OPENAI_KEY ? `openai:${OPENAI_MODEL}` : 'local-engine');

// ---------------------------------------------------------------- helpers
const CHANNEL_LABELS = {
  instagram: 'Instagram',
  tiktok: 'TikTok',
  facebook: 'Facebook',
  ouedkniss: 'Ouedkniss',
  website: 'Website / E-shop',
  whatsapp: 'WhatsApp Business',
};
const GOAL_LABELS = {
  awareness: 'Brand awareness',
  sales: 'Increase sales',
  followers: 'Grow followers',
  launch: 'Product launch',
  leads: 'Generate leads',
};
const fmtDZD = (n) => `${Math.round(n).toLocaleString('fr-DZ')} DZD`;
const clamp = (n, a, b) => Math.max(a, Math.min(b, n));
const slug = (s) => s.replace(/[^\p{L}\p{N}]+/gu, '').toLowerCase();

function hash(str) {
  let h = 2166136261;
  for (const ch of str) h = Math.imul(h ^ ch.codePointAt(0), 16777619);
  return h >>> 0;
}
function pick(arr, seed, n = 1) {
  const out = [];
  const copy = [...arr];
  let s = seed;
  while (out.length < n && copy.length) {
    s = (Math.imul(s, 1103515245) + 12345) >>> 0;
    out.push(copy.splice(s % copy.length, 1)[0]);
  }
  return n === 1 ? out[0] : out;
}

// ---------------------------------------------------------------- LLM call
async function llm(system, payload) {
  const res = await fetch(`${OPENAI_BASE}/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${OPENAI_KEY}` },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      temperature: 0.7,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: JSON.stringify(payload) },
      ],
    }),
    signal: AbortSignal.timeout(60_000),
  });
  if (!res.ok) throw new Error(`OpenAI ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const data = await res.json();
  return JSON.parse(data.choices[0].message.content);
}

async function withFallback(stage, system, payload, local) {
  if (!OPENAI_KEY) return { ...local(), _source: 'local-engine' };
  try {
    const out = await llm(system, payload);
    return { ...local(), ...out, _source: `openai:${OPENAI_MODEL}` };
  } catch (err) {
    console.warn(`[ai] ${stage} LLM failed, using local engine:`, err.message);
    return { ...local(), _source: 'local-engine (fallback)' };
  }
}

const SYS_BASE =
  'You are AKMA, a senior marketing strategist specialised in the Algerian (DZ) market ' +
  '(Instagram, TikTok, Facebook, Ouedkniss, cash-on-delivery culture, Darija/French/Arabic audiences, prices in DZD). ' +
  'Reply ONLY with a JSON object matching the requested schema.';

// ============================================================ STAGE 1: core AI analysis
// Classifies the client and computes scores that the 3 parallel branches build on.
export async function coreAnalysis(client) {
  const local = () => {
    const budget = Number(client.budget) || 0;
    const channels = client.channels || [];
    const goals = client.goals || [];
    const descLen = (client.description || '').trim().length;

    const budgetTier = budget >= 150000 ? 'high' : budget >= 50000 ? 'medium' : 'low';
    const budgetScore = clamp(Math.round((budget / 200000) * 100), 5, 100);
    const channelScore = clamp(channels.length * 20, 0, 100);
    const clarityScore = clamp(Math.round(descLen / 3) + (client.targetAudience ? 30 : 0), 10, 100);
    const focusScore = goals.length === 0 ? 30 : goals.length <= 2 ? 95 : goals.length === 3 ? 70 : 50;
    const readiness = Math.round(budgetScore * 0.3 + channelScore * 0.2 + clarityScore * 0.3 + focusScore * 0.2);

    const stage =
      readiness >= 75 ? 'Scale-up' : readiness >= 50 ? 'Growth' : readiness >= 30 ? 'Early traction' : 'Launch';

    return {
      segment: `${client.industry || 'Retail'} · ${client.wilaya || 'Algeria'}`,
      budgetTier,
      businessStage: stage,
      readinessScore: readiness,
      scores: { budget: budgetScore, channels: channelScore, clarity: clarityScore, focus: focusScore },
      primaryGoal: GOAL_LABELS[goals[0]] || 'Brand awareness',
      summary:
        `${client.businessName} is at the "${stage}" stage with a ${budgetTier} monthly budget ` +
        `(${fmtDZD(budget)}). Marketing readiness is ${readiness}/100, driven mostly by ` +
        `${Object.entries({ budget: budgetScore, channels: channelScore, clarity: clarityScore, focus: focusScore })
          .sort((a, b) => b[1] - a[1])[0][0]}.`,
    };
  };
  return withFallback(
    'core',
    SYS_BASE +
      ' Schema: {segment:string, budgetTier:"low"|"medium"|"high", businessStage:string, readinessScore:0-100, ' +
      'scores:{budget,channels,clarity,focus}, primaryGoal:string, summary:string}',
    { task: 'core_analysis', client },
    local
  );
}

// ============================================================ BRANCH A: detailed analysis report
export async function analysisReport(client, core) {
  const local = () => {
    const seed = hash(client.businessName + client.email);
    const channels = client.channels || [];
    const has = (c) => channels.includes(c);

    const strengths = [
      client.description && 'Clear product offer described by the founder',
      core.budgetTier !== 'low' && 'Budget allows consistent paid promotion',
      channels.length >= 3 && 'Multi-channel presence already in place',
      has('tiktok') && 'Present on TikTok, the fastest-growing platform among Algerian youth',
      has('ouedkniss') && 'Listed on Ouedkniss – strong purchase intent traffic',
      'Local brand advantage: faster delivery and COD trust vs. imports',
    ].filter(Boolean);
    const weaknesses = [
      core.budgetTier === 'low' && 'Limited budget – must rely on organic content & UGC',
      !has('instagram') && 'Missing Instagram, the main discovery channel for fashion in DZ',
      !has('website') && 'No owned e-shop – dependent on social DMs for orders',
      (client.goals || []).length > 3 && 'Too many simultaneous goals dilute impact',
      !client.targetAudience && 'Target audience not precisely defined',
    ].filter(Boolean);
    const opportunities = pick(
      [
        'Ramadan & Eid peaks: plan collections and promos 4 weeks ahead',
        'Back-to-school (September) demand for streetwear & sneakers',
        'Micro-influencers (5k–50k) in Algiers, Oran & Constantine offer high ROI',
        '58-wilaya delivery via Yalidine / ZR Express expands reach beyond your wilaya',
        'Darija-language short-form video drives much higher engagement',
        'Limited "drops" create scarcity and repeat visits',
        'Summer diaspora return (July–August) boosts spending',
      ],
      seed,
      4
    );
    const threats = pick(
      [
        'Cheap imported replicas competing on price',
        'High return rate on cash-on-delivery orders',
        'Algorithm changes reducing organic reach',
        'Competitors copying designs quickly',
        'Currency fluctuation raising import/material costs',
      ],
      seed >> 3,
      3
    );

    const ageMatch = (client.targetAudience || '').match(/(\d{2})\s*[-–à]\s*(\d{2})/);
    const persona = {
      name: pick(['Yacine', 'Amine', 'Lina', 'Sara', 'Rayane', 'Nour'], seed),
      age: ageMatch ? `${ageMatch[1]}–${ageMatch[2]}` : '18–30',
      location: client.wilaya || 'Algiers',
      description:
        client.targetAudience ||
        'Urban, trend-driven, discovers brands on Instagram & TikTok, prefers cash on delivery.',
      motivations: ['Stand out with unique style', 'Good quality for the price', 'Fast, trusted delivery'],
      objections: ['Is the quality real?', 'Delivery fees to my wilaya', 'Sizing uncertainty'],
    };

    const recommendedChannels = ['instagram', 'tiktok', 'facebook', 'ouedkniss', 'whatsapp', 'website']
      .map((c) => ({
        channel: CHANNEL_LABELS[c],
        fit: clamp(
          { instagram: 92, tiktok: 88, facebook: 70, ouedkniss: 65, whatsapp: 60, website: 55 }[c] +
            (has(c) ? 5 : 0) +
            ((seed >> c.length) % 7) -
            3,
          0,
          100
        ),
        active: has(c),
      }))
      .sort((a, b) => b.fit - a.fit);

    return {
      swot: { strengths, weaknesses, opportunities, threats },
      persona,
      recommendedChannels,
      insights: [
        `Primary goal "${core.primaryGoal}" should drive 70% of the effort for the next 30 days.`,
        `Top channel fit: ${recommendedChannels[0].channel} (${recommendedChannels[0].fit}/100).`,
        core.readinessScore < 50
          ? 'Focus on fundamentals first: brand identity, product photos, clear pricing & delivery info.'
          : 'Fundamentals are solid – time to invest in paid acquisition and influencer partnerships.',
      ],
    };
  };
  return withFallback(
    'analysis',
    SYS_BASE +
      ' Schema: {swot:{strengths:string[],weaknesses:string[],opportunities:string[],threats:string[]}, ' +
      'persona:{name,age,location,description,motivations:string[],objections:string[]}, ' +
      'recommendedChannels:[{channel,fit:0-100,active:boolean}], insights:string[]}',
    { task: 'analysis_report', client, core },
    local
  );
}

// ============================================================ BRANCH B: marketing plan
export async function marketingPlan(client, core) {
  const local = () => {
    const budget = Number(client.budget) || 0;
    const channels = (client.channels || []).length ? client.channels : ['instagram', 'tiktok'];
    const weights = { instagram: 35, tiktok: 30, facebook: 20, ouedkniss: 10, website: 15, whatsapp: 5 };
    const adShare = core.budgetTier === 'low' ? 0.6 : 0.7;
    const influencerShare = core.budgetTier === 'low' ? 0.25 : 0.2;
    const contentShare = 1 - adShare - influencerShare;
    const totalW = channels.reduce((s, c) => s + (weights[c] || 10), 0);

    const allocation = [
      ...channels.map((c) => ({
        item: `Ads · ${CHANNEL_LABELS[c] || c}`,
        amount: Math.round((budget * adShare * (weights[c] || 10)) / totalW),
      })),
      { item: 'Micro-influencers / UGC', amount: Math.round(budget * influencerShare) },
      { item: 'Content production (photo/video)', amount: Math.round(budget * contentShare) },
    ].map((a) => ({ ...a, percent: budget ? Math.round((a.amount / budget) * 100) : 0, label: fmtDZD(a.amount) }));

    const g = client.goals || [];
    const weeks = [
      {
        week: 1,
        theme: 'Foundation & Brand Setup',
        actions: [
          'Optimise bios, highlights & link-in-bio with delivery/COD info',
          'Shoot a batch of 20+ product photos and 6 short videos',
          'Set up Meta Pixel / TikTok Pixel and a WhatsApp Business catalogue',
        ],
      },
      {
        week: 2,
        theme: g.includes('launch') ? 'Teaser & Launch' : 'Awareness Push',
        actions: [
          g.includes('launch') ? 'Run 3-day countdown teasers, then launch drop' : 'Launch reach campaign targeting persona',
          'Publish 1 Reel/TikTok per day in Darija',
          'Contact 5 micro-influencers in target wilayas',
        ],
      },
      {
        week: 3,
        theme: g.includes('sales') ? 'Conversion Campaign' : 'Engagement & Community',
        actions: [
          'Retarget video viewers & profile visitors with carousel ads',
          'Run a giveaway (follow + tag 2 friends) to boost reach',
          'Share customer reviews & unboxing UGC daily in stories',
        ],
      },
      {
        week: 4,
        theme: 'Optimise & Scale',
        actions: [
          'Kill ads with CTR < 1%; double budget on top 2 creatives',
          'Launch limited offer (free delivery to 58 wilayas for 48h)',
          'Review KPIs and plan next month in the AKMA dashboard',
        ],
      },
    ];

    const reachPerDZD = core.budgetTier === 'low' ? 1.8 : 1.5;
    return {
      objective: `${core.primaryGoal} for ${client.businessName} in 30 days`,
      strategy:
        core.budgetTier === 'low'
          ? 'Organic-first: daily short-form video + UGC, with small boosted posts on the best performers.'
          : 'Full-funnel: reach campaigns → retargeting → conversion, supported by micro-influencers.',
      budget: { monthly: budget, label: fmtDZD(budget), allocation },
      weeks,
      kpis: [
        { metric: 'Estimated reach', target: Math.round(budget * reachPerDZD).toLocaleString('fr-DZ') },
        { metric: 'Follower growth', target: `+${clamp(Math.round(budget / 200), 150, 5000)}` },
        { metric: 'Engagement rate', target: '≥ 4%' },
        { metric: 'Orders / leads', target: `${clamp(Math.round(budget / 2500), 10, 400)}` },
        { metric: 'Cost per order', target: `≤ ${fmtDZD(clamp(budget / Math.max(1, budget / 2500), 400, 2500))}` },
      ],
    };
  };
  return withFallback(
    'marketing',
    SYS_BASE +
      ' Schema: {objective, strategy, budget:{monthly:number,label,allocation:[{item,amount,percent,label}]}, ' +
      'weeks:[{week,theme,actions:string[]}], kpis:[{metric,target}]}. Budget amounts in DZD must sum to the monthly budget.',
    { task: 'marketing_plan', client, core },
    local
  );
}

// ============================================================ BRANCH C: content
export async function contentPack(client, core) {
  const local = () => {
    const seed = hash(client.businessName + (client.industry || ''));
    const name = client.businessName;
    const tag = slug(name);
    const product = (client.industry || 'streetwear').toLowerCase();
    const tone = client.tone || 'bold';

    const hooks = {
      bold: ['🔥 New drop alert!', 'No copies. Only originals.', 'Built for the streets of DZ.'],
      friendly: ['Hey family! 👋', 'You asked, we listened 💛', 'Something special just landed…'],
      premium: ['Crafted with intention.', 'Quality you can feel.', 'The new standard.'],
      funny: ['Your wardrobe called… it needs help 😂', 'POV: you finally found your style', 'Mama approved ✅'],
    }[tone] || ['New drop!'];

    const captions = [
      `${hooks[0]} The new ${product} collection by ${name} is here. Limited pieces – DM to order 📩 Livraison 58 wilayas 🇩🇿`,
      `${hooks[1]} Every ${name} piece is checked by hand before shipping. Paiement à la livraison ✅`,
      `${hooks[2]} Which one are you picking: 1, 2 or 3? Comment below 👇`,
      `Real customers, real fits 📸 Tag us @${tag} to be featured!`,
      `48H ONLY ⏳ Free delivery on all ${name} orders. Don't sleep on it.`,
    ];

    const ideas = pick(
      [
        { format: 'Reel', idea: 'Outfit transition: 3 looks in 10 seconds on a trending sound' },
        { format: 'TikTok', idea: '"Packing your order" ASMR with the brand packaging' },
        { format: 'Reel', idea: 'Street interviews in Darija: "Rate this fit /10"' },
        { format: 'Carousel', idea: 'Size guide with real measurements & model heights' },
        { format: 'Story', idea: 'Poll: which colourway should we restock?' },
        { format: 'TikTok', idea: 'Behind the scenes: from design to finished piece' },
        { format: 'Reel', idea: 'Customer unboxing compilation (UGC)' },
        { format: 'Carousel', idea: 'Original vs. fake: how to spot quality' },
      ],
      seed,
      6
    );

    const days = ['Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'];
    const calendar = days.map((day, i) => ({
      day,
      time: ['20:00', '21:00', '19:30', '20:30', '21:00', '14:00', '22:00'][i],
      format: ideas[i % ideas.length].format,
      topic: ideas[i % ideas.length].idea,
    }));

    const hashtags = [
      `#${tag}`,
      '#dz',
      '#algerie',
      '#streetweardz',
      `#${slug(client.wilaya || 'alger')}`,
      '#modedz',
      '#livraison58wilayas',
      `#${slug(product)}`,
      '#dzfashion',
      '#madeinalgeria',
    ];

    return {
      tone,
      captions,
      hashtags,
      reelIdeas: ideas,
      calendar,
      adCopy: {
        headline: `${name} – ${product} made for you`,
        primaryText: `Discover the new ${name} collection. Premium quality, fair prices, cash on delivery across all 58 wilayas. 🇩🇿`,
        cta: (client.goals || []).includes('sales') ? 'Shop Now' : 'Learn More',
      },
      darija: [
        `Jdid ${name} wsel! 🔥 Commandi f DM, livraison l 58 wilaya.`,
        `Qualité top w prix m3qoul – ${name} m3ak dima 💯`,
      ],
    };
  };
  return withFallback(
    'content',
    SYS_BASE +
      ' Schema: {tone, captions:string[5], hashtags:string[10], reelIdeas:[{format,idea}], ' +
      'calendar:[{day,time,format,topic}] (7 days starting Saturday), adCopy:{headline,primaryText,cta}, darija:string[2]}',
    { task: 'content_pack', client, core },
    local
  );
}
